### ISSUE TITLE
Port HW3 into group repo and update README.md

### ISSUE THREAD

**Issue by Dorfu** [UC-Irvine-CS175/final-project-buff-mice#4]
#### Description
Port HW3 files into final project repo. This is in preparation for the upcoming PR2: merge pca_tsne.py, vis_utils, bps_datamodule.py

#### Files
src/dataset/bps_datamodule.py
src/unsupervised/pca_tsne.py
src/unsupervised/resnet101.py

#### Tasks
- [ ] Open new branch for merging HW3 content
- [ ] Add updated & tested files
- [ ] Edit README.md to include info about content from both HW imports
